### PR TITLE
Add missing type of `asEmailString()` according to PR #158

### PR DESCRIPTION
**Pull request by hckhanh**
Hi @evanshortiss, I realize that the type of `asEmailString()` is missing, I put some changes

### CODE REVIEW

**Comment by evanshortiss** [comment]
Thank you! Could you also add it to the `VariableAccessors` here: https://github.com/evanshortiss/env-var/blob/master/env-var.d.ts#L107

**Review by evanshortiss — CHANGES_REQUESTED** [review]
Looks good. Just need to make sure it's also in the VariableAccessors interface.

**Comment by hckhanh** [comment]
ok @evanshortiss, I add the missing type to `VariableAccessors` interface.

**Comment by evanshortiss** [comment]
Releasing as 7.3.0, thanks @hckhanh !

**Pull request merged**
