### PR TITLE
Match from inputs to ProcessEnv definition

### PR DESCRIPTION
**Pull request by moltar**
Official declaration for `ProcessEnv` is:

```ts
    interface ProcessEnv {
        [key: string]: string | undefined;
    }
```

### CODE REVIEW

**Comment by moltar** [comment]
Is it maybe better to just use `ProcessEnv` type as input entirely and not re-create it?

**Comment by shawnmclean** [comment]
Well...it's good to check the existing PRs before doing something. I ended up implementing your `ProcessEnv` suggestion anyways so its not really a waste of time. (https://github.com/evanshortiss/env-var/pull/53)

**Comment by evanshortiss** [comment]
> Is it maybe better to just use ProcessEnv type as input entirely and not re-create it?

This would be ideal. If you're happy with the @shawnmclean PR I can merge that instead.

**Comment by moltar** [comment]
Closing this in favour of #53

**Pull request closed without merging**
