### PR TITLE
asArray accepting env-variable with one value (without delimiter) and still ensure is there at least one value passed

### PR DESCRIPTION
**Pull request by gabrieloczkowski**
asArray accepting env-variable with one value (without delimiter) and still ensure is there at least one value passed

### CODE REVIEW

**Comment by tomsquest** [comment]
:+1: 

- Maybe add test for `,value` (prefix = comma)

**Comment by evanshortiss** [comment]
@gabrieloczkowski I'm going to merge #55 first since it's a minor release. After I've merged and released that as 4.1.0 I will merge this and release as 5.0.0 👍

**Comment by evanshortiss** [comment]
@tomsquest, good call. @gabrieloczkowski could you add that test then I will merge and do the release.

Thanks for the contributions all 🙏

**Comment by gabrieloczkowski** [comment]
@tomsquest test added.
@evanshortiss I also fixed typo 'delimeter' -> 'delimiter'.

**Pull request merged**
